### ISSUE TITLE
config.userID should be a valid userID

### ISSUE THREAD

**Issue by kmf** [cubzh/cubzh#464]
# Steps to Reproduce
- In the Items Gallery 
- clicked on my Item 
- then Clicked on my userID

![CleanShot 2024-02-11 at 13 49 23](https://github.com/cubzh/cubzh/assets/78700/d478f343-a801-4951-8428-da98db4bf4da)

**Comment by gdevillele** [comment]
It has been fixed 👍 

<img width="912" alt="Screenshot 2024-04-23 at 14 31 19" src="https://github.com/cubzh/cubzh/assets/939999/56cd97e9-bcc9-4525-ae17-5302b31ba13e">
