### ISSUE TITLE
Request: Add "avatarDidLoad"

### ISSUE THREAD

**Issue by Boumety** [cubzh/cubzh#525]
Add "avatarDidLoad" with a function as a callback.

This could be useful for games that change the wearables of the Player.

**Comment by gdevillele** [comment]
Note : this is in the contexte of `ui_avatar` module, `get` function

**Comment by aduermael** [comment]
We also need to override/cancel ongoing requests when setting wearables. It shouldn't be necessary to wait for requests to end to update avatar parts. 
This `avatarDidLoad` callback would still be useful either way.

**Comment by aduermael** [comment]
I believe this issue is outdated. 
It's now possible to change avatar wearables, naturally overriding / cancelling ongoing requests.
