### ISSUE TITLE
Crash when dividing Color

### ISSUE THREAD

**Issue by gdevillele** [cubzh/cubzh#580]
@Nanskip reported that dividing a `Color` crashes the Cubzh app on Windows

**Comment by aduermael** [comment]
@Nanskip I tried this without issues: 
```lua
local v = Color(255,0,0) // 10
print("Color(255,0,0) // 10 ->", v)
v = Color(255,0,0) / 5
print("Color(255,0,0) / 5 ->", v)
```
Can you provide more details?

**Comment by aduermael** [comment]
Closing as we still can't repro.
