### ISSUE TITLE
Lua error in Tutorial n°1 : Tutoworld

### ISSUE THREAD

**Issue by Hfrancillon** [cubzh/cubzh#6]
I completed the tutoworld and I encountered an error on this line (twice) : 140 and 185

```lua
UI:Crosshair = true
```

The solution is : 
```lua
UI.Crosshair = true
```

**Comment by RacineC** [comment]
Thank you for the report. This will be fix quickly!

**Comment by gdevillele** [comment]
It has been fixed ✅
