### ISSUE TITLE
[Wasm] Browsers issues when playing on Dojo version

### ISSUE THREAD

**Issue by caillef** [cubzh/cubzh#624]
Link:
https://app.cu.bzh/editions/dojo-1.0.0.alpha6/?script=github.com/caillef/diamond-pit:f097e7f8a4b306cc09452087476458a376481021

On my computer:
- Brave and Safari works fine
- Chrome has a black skybox and does not work before resizing the window

On other computers:
- Works only on Safari, Chrome does not work at all
- Brave does not work on another mac but it works on my computer

Works = no need to resize to display + you can move
Does not work = black skybox, and even after resizing the window, can't control

### How to run locally

1) checkout to dojo-and-vscode branches on both repos
2) cd wasm
3) unzip emsdk-3.1.38.zip
4) cd emsdk-3.1.38
5) ./emsdk install 3.1.38
6) ./emsdk activate 3.1.38
7) source emsdk_env.sh

8) make `editions` directory in go/cu.bzh/wasmserver
9) go to wasm/Particubes
10) `./build.sh && cp -r build/output/* ../../go/cu.bzh/wasmserver/editions/dojo-1.0.0.alpha6`
11) go to go/cu.bzh/wasmserver
check that the main.go has this line `err = http.ListenAndServe(":8081", router)`
12) go run main.go
13) visit `http://localhost:8081/editions/dojo-1.0.0.alpha6/?script=github.com/caillef/diamond-pit:f097e7f8a4b306cc09452087476458a376481021`

**Comment by ArthurVoxowl** [comment]
It will be worth testing this again once https://github.com/voxowl/particubes-private/pull/4843 is merged

**Comment by caillef** [comment]
PR 4843 fixed it ✅  Closing
