### ISSUE TITLE
JSON decode issues when string entries contain `\` characters

### ISSUE THREAD

**Issue by aduermael** [cubzh/cubzh#633]
Reported by @sysfab: https://discord.com/channels/355905150528913409/766205280353648640/1279112722906353784

<img width="956" alt="Screenshot 2024-08-30 at 18 28 48" src="https://github.com/user-attachments/assets/406ceb31-f134-40c8-8a19-b69d32437f61">

**Comment by aduermael** [comment]
@sysfab I did find escaping errors in the encoder.
But, I believe you still need to manually escape the `\` in your string, it should be: 
`"cubic-dungeons\\client.lua > New section \"START\" ...`

Imagine if `client.lua` was `tadam.lua`, how would the parser make a difference between path separator `\` and tab character `\t`? (`cubic-dungeons\tadam.lua`)

**Comment by sysfab** [comment]
@aduermael my string is fine, it already has escaped characters, it the lua it works, but in json it`s not
