### ISSUE TITLE
Issue when adding a friend as a <13yo + newbie without username set

### ISSUE THREAD

**Issue by soliton-x** [cubzh/cubzh#641]
When adding a friend as a <13yo + newbie without a username set, the friend request is sent but the other user doesn't seem to receive the request. 

<img width="670" alt="Capture d’écran 2024-09-05 à 11 40 25" src="https://github.com/user-attachments/assets/39058472-cdbd-45f9-8c4d-7111a0044383">

Added: Notilos, Gaetan, Aduermael.

**Comment by aduermael** [comment]
I think it happened to me once with a similar configuration, but the username was still forced within signup so it might not be the reason. 
But there could be an issue when adding friends with newly created account yes.

**Comment by aduermael** [comment]
@soliton-x Is it a 100% repro?

**Comment by gdevillele** [comment]
I received the push notification but don’t see the invite inside the app
