### ISSUE TITLE
Windows : ALT+TAB and back, while playing in a world, breaks the keyboard events

### ISSUE THREAD

**Issue by gdevillele** [cubzh/cubzh#642]
focusing the chat text input repairs things.

**Comment by maiarafag** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by ArthurVoxowl** [comment]
Still couldn't repro this issue as of `0.1.6`

**Comment by gdevillele** [comment]
let's close it then
