### ISSUE TITLE
CI jobs random crash

### ISSUE THREAD

**Issue by XLegland** [cubzh/cubzh#68]
Sometimes the core tests CI crashes, but if we run it again it does not. Example of a crash: https://github.com/cubzh/cubzh/actions/runs/3469993278/jobs/5797646806

**Comment by gdevillele** [comment]
I had a look... it's a precision issue (epsilon is too small on CI, but works fine on macOS at least 🤨)

**Comment by gdevillele** [comment]
we have not seen this crash on the CI for a long time. We'll increase the epsilon value if we encounter it again.
