### ISSUE TITLE
Ubuntu version on the CI

### ISSUE THREAD

**Issue by XLegland** [cubzh/cubzh#94]
Currently we use ubuntu@latest for the CI, maybe we should specify a version
![image](https://user-images.githubusercontent.com/33065418/207375609-b30ea966-a47f-4c8e-bdd7-3537e5bc91cb.png)

**Comment by gdevillele** [comment]
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

Good point. Apparently they use the latest LTS version for `ubuntu-latest`, so we can leave it as-is IMO. 🙂
